### ISSUE TITLE
Example github action code

### ISSUE THREAD

**Issue by Milokita** [cuhk-haosun/code-docker-fastqc#18]
```
# This is a basic workflow that is manually triggered

name: Github action for running docker fastqc 

on:
  workflow_dispatch:
    inputs:
      INPUT_PATH:
        description: 'Input path for the files'
        default: '/share/home/grp-sunhao/zhaoxing/pub/example/np.human.fastq.pico'
        required: true
        type: string

      OUTPUT_PATH:
        description: 'Output path for the files'
        default: '/share/home/grp-sunhao/zx/dev/np.human.fastq/output'
        required: true
        type: string

      JOB_NAME:
        description: 'Give your job a name'
        default: 'fastqc'
        required: true
        type: string

      THREAD_NUM:
        description: 'Thread number for alignment etc.'
        default: "8"
        required: false
        type: string

jobs:
  fastqc:
    name: Fastq Quality Control
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Pull Docker image
      run: docker pull ghcr.io/cuhk-haosun/code-docker-fastqc:latest

    - name: Run container with environment variables
      run: |
          docker run --name "${{ github.event.inputs.JOB_NAME }}_container" \
            -v ${{ github.event.inputs.INPUT_PATH }}:/mnt/in \
            -v ${{ github.event.inputs.OUTPUT_PATH }}:/mnt/out \
            -e JOB_NAME=${{ github.event.inputs.JOB_NAME }} \
            -e THREAD_NUM=${{ github.event.inputs.THREAD_NUM }} \
            ghcr.io/cuhk-haosun/code-docker-fastqc:latest

    - name: Stop and remove container
      run: |
          docker stop "${{ github.event.inputs.JOB_NAME }}_container"
          docker rm "${{ github.event.inputs.JOB_NAME }}_container"
          
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch-suffix: short-commit-hash
        commit-message: |
          Add result for ${{ github.event.inputs.JOB_NAME }}
          This is auto uploaded commit
        branch: result-${{ github.event.inputs.JOB_NAME }}
        delete-branch: true
        title: '[Demo] add report for nanopore DNA seq run ${{ github.event.inputs.JOB_NAME }}'
        body: |
            Update report
            - Auto-generated by github action `Pipeline for nanopore DNA sequencing`
```
